Add support for Audio Toolbox output (MacOS)
devgianlu/go-librespot pull request #153
Opened 2024-12-10 10:51 UTC by stronk-dev

Adapted from https://github.com/devgianlu/go-librespot/pull/59

Notable changes:
- Instead of overwriting `newOutput`, make it a separate `toolboxOutput` which can be activated by setting the backend to `audio-toolbox`.
- Stubs added for outputs with `go:build` constraint printing a generic 'unsupported' message
NOTE: we could enhance the stubs so that the output knows which outputs are supported and then automatically choose a platform-specific output like `audio-toolbox`.
- Use a C struct to give the audio callback (which asks for samples when required) access to the reader directly.
NOTE: depending on how the float32 reader is implemented, maybe having a FIFO buffer in the output could be useful? Ideally these kinds of callbacks have instant access to data without blockage (and fill remaining samples with silence if there's no data in the buffer).
Removing the local buffer in the output and having the CB read directly does not seem to cause any issues so far...
- Major simplification of buffer initialization and buffering logic for easier maintainability
- Generic code cleanup: added some comments, checks, error cases, etc...

The PR is pronbably ready for review as-is, but there might be some minor issues like making sure that `out.err` gets set where necessary, more comments and testing to see how it handles error cases.

2024-12-11 10:59 UTC, stronk-dev commented
Has been mostly stable. I did ran into some issues at one point where during a track switch the `out.reader.Read` would give an EOF. At the moment this is a hard error, although we could just add silent samples when there is a buffer underflow.

2024-12-11 18:34 UTC, devgianlu requested changes
In addition to the comments, I would advise to not capitalize log messages to match go guidelines.

I think this is good stuff to add even if it's not perfect. We can improve on it overtime, thank you for putting the work to revisit it!

2024-12-11 18:34 UTC, devgianlu commented on output/driver-audio-toolbox.go
> +	ctx := (*C.AudioContext)(C.malloc(C.size_t(unsafe.Sizeof(C.AudioContext{}))))
This can be extract to a C function like the `free` one.

2024-12-11 18:34 UTC, devgianlu commented on output/driver-audio-toolbox.go
> +		return nil, errors.New("failed to allocate AudioContext")
Do not create the error twice, use a local variable.

2024-12-11 18:34 UTC, devgianlu commented on output/driver-audio-toolbox.go
> +	stopChan   chan struct{}
This can be removed.

2025-01-16 10:46 UTC, stronk-dev commented
(just wanted to note that I haven't forgot about the PR - I'll rebase and resolve the outstanding issues somewhere this month)

2025-06-26 10:55 UTC, stronk-dev commented
Turns out I did forget about it. Rebased & adjusted the PR. LMK if more changes are required!

2025-07-12 12:28 UTC, devgianlu approved these changes

2025-07-12 12:29 UTC, merged